name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master"  ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: 构建Docker镜像
      run: |
        docker build -t robotics-ci:latest .
        
    - name: 运行构建容器并执行构建
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          robotics-ci:latest \
          bash -c "
            echo '开始自动化构建流程...' &&
            echo '1. 更新系统依赖库...' &&
            ./tools/lib_update.sh &&
            echo '2. 执行项目构建...' &&
            ./tools/build.sh &&
            echo '3. 验证构建产物...' &&
            ls -la build/ &&
            ls -la build/examples/ &&
            echo '构建完成！'
          "
    - name: 输出构建信息
      run: |
        echo "构建分支: ${{ github.ref_name }}"
        echo "提交哈希: ${{ github.sha }}"
        echo "构建时间: $(date)"